

export const setDataTypes = typeData => ({
    type: 'TOTAL_CONFIRMED',
    typeData
})

export const DataTypes = {
    TOTAL_CONFIRMED: 'TOTAL_CONFIRMED',
    TOTAL_DEATH: 'TOTAL_DEATH',
    TOTAL_RECOVERED: 'TOTAL_RECOVERED',
    NEW_CONFIRMED: 'NEW_CONFIRMED',
    NEW_DEATH: 'NEW_DEATH',
    NEW_RECOVERED: 'NEW_RECOVERED',
    TOTAL_POPULATION_COUNFIRM: 'TOTAL_POPULATION_COUNFIRM',
    TOTAL_POPULATION_DEATH: 'TOTAL_POPULATION_DEATH',
    TOTAL_POPULATION_RECOVERED: 'TOTAL_POPULATION_RECOVERED',
    NEW_POPULATION_CONFIRMED: 'NEW_POPULATION_CONFIRMED',
    NEW_POPULATION_DEATH: 'NEW_POPULATION_DEATH',
    NEW_POPULATION_RECOVERED: 'NEW_POPULATION_RECOVERED',
}

