export const stateCountries = {
    TOTAL_CONFIRMED: 'TOTAL_CONFIRMED_COUNTRIES',
    TOTAL_DEATH: 'TOTAL_DEATH_COUNTRIES',
    TOTAL_RECOVERED: 'TOTAL_RECOVERED_COUNTRIES',
    NEW_CONFIRMED: 'NEW_CONFIRMED_COUNTRIES',
    NEW_DEATH: 'NEW_DEATH_COUNTRIES',
    NEW_RECOVERED: 'NEW_RECOVERED_COUNTRIES',
    TOTAL_POPULATION_COUNFIRM: 'TOTAL_POPULATION_COUNFIRM',
    TOTAL_POPULATION_DEATH: 'TOTAL_POPULATION_DEATH',
    TOTAL_POPULATION_RECOVERED: 'TOTAL_POPULATION_RECOVERED',
    NEW_POPULATION_CONFIRMED: 'NEW_POPULATION_CONFIRMED',
    NEW_POPULATION_DEATH: 'NEW_POPULATION_DEATH',
    NEW_POPULATION_RECOVERED: 'NEW_POPULATION_RECOVERED',
}

export const stateTotal = {
    TOTAL_CONFIRMED: 'TOTAL_CONFIRMED',
    TOTAL_DEATH: 'TOTAL_DEATH',
    TOTAL_RECOVERED: 'TOTAL_RECOVERED',
    NEW_CONFIRMED: 'NEW_CONFIRMED',
    NEW_DEATH: 'NEW_DEATH',
    NEW_RECOVERED: 'NEW_RECOVERED',
    TOTAL_POPULATION_COUNFIRM: 'POPULATION_TOTAL_CONFIRMED',
    TOTAL_POPULATION_DEATH: 'POPULATION_TOTAL_DEATH',
    TOTAL_POPULATION_RECOVERED: 'POPULATION_TOTAL_RECOVERED',
    NEW_POPULATION_CONFIRMED: 'POPULATION_NEW_CONFIRMED',
    NEW_POPULATION_DEATH: 'POPULATION_NEW_DEATH',
    NEW_POPULATION_RECOVERED: 'POPULATION_NEW_RECOVERED',
}

export const stateChart = {
    TOTAL_CONFIRMED: 'CASES_COORDINATES',
    TOTAL_DEATH: 'DEATHS_COORDINATES',
    TOTAL_RECOVERED: 'RECOVERED_COORDINATES',
    NEW_CONFIRMED: 'DAYS_CASES_COORDINATES',
    NEW_DEATH: 'DAYS_DEATHS_COORDINATES',
    NEW_RECOVERED: 'DAYS_RECOVERED_COORDINATES',
    TOTAL_POPULATION_COUNFIRM: 'CASES_COORDINATES',
    TOTAL_POPULATION_DEATH: 'DEATHS_COORDINATES',
    TOTAL_POPULATION_RECOVERED: 'RECOVERED_COORDINATES',
    NEW_POPULATION_CONFIRMED: 'DAYS_CASES_COORDINATES',
    NEW_POPULATION_DEATH: 'DAYS_DEATHS_COORDINATES',
    NEW_POPULATION_RECOVERED: 'DAYS_RECOVERED_COORDINATES',
}

export const stateColumDeath = {
    TOTAL_CONFIRMED: 'TOTAL_DEATH',
    TOTAL_DEATH: 'TOTAL_DEATH',
    TOTAL_RECOVERED: 'TOTAL_DEATH',
    NEW_CONFIRMED: 'NEW_DEATH',
    NEW_DEATH: 'NEW_DEATH',
    NEW_RECOVERED: 'NEW_DEATH',
    TOTAL_POPULATION_COUNFIRM: 'POPULATION_TOTAL_DEATH',
    TOTAL_POPULATION_DEATH: 'POPULATION_TOTAL_DEATH',
    TOTAL_POPULATION_RECOVERED: 'POPULATION_TOTAL_DEATH',
    NEW_POPULATION_CONFIRMED: 'POPULATION_NEW_DEATH',
    NEW_POPULATION_DEATH: 'POPULATION_NEW_DEATH',
    NEW_POPULATION_RECOVERED: 'POPULATION_NEW_DEATH',
}

export const stateColumConfirmed = {
    TOTAL_CONFIRMED: 'TOTAL_CONFIRMED',
    TOTAL_DEATH: 'TOTAL_CONFIRMED',
    TOTAL_RECOVERED: 'TOTAL_CONFIRMED',
    NEW_CONFIRMED: 'NEW_CONFIRMED',
    NEW_DEATH: 'NEW_CONFIRMED',
    NEW_RECOVERED: 'NEW_CONFIRMED',
    TOTAL_POPULATION_COUNFIRM: 'POPULATION_TOTAL_CONFIRMED',
    TOTAL_POPULATION_DEATH: 'POPULATION_TOTAL_CONFIRMED',
    TOTAL_POPULATION_RECOVERED: 'POPULATION_TOTAL_CONFIRMED',
    NEW_POPULATION_CONFIRMED: 'POPULATION_NEW_CONFIRMED',
    NEW_POPULATION_DEATH: 'POPULATION_NEW_CONFIRMED',
    NEW_POPULATION_RECOVERED: 'POPULATION_NEW_CONFIRMED',
}

export const stateColumRecovered = {
    TOTAL_CONFIRMED: 'TOTAL_RECOVERED',
    TOTAL_DEATH: 'TOTAL_RECOVERED',
    TOTAL_RECOVERED: 'TOTAL_RECOVERED',
    NEW_CONFIRMED: 'NEW_RECOVERED',
    NEW_DEATH: 'NEW_RECOVERED',
    NEW_RECOVERED: 'NEW_RECOVERED',
    TOTAL_POPULATION_COUNFIRM: 'POPULATION_TOTAL_RECOVERED',
    TOTAL_POPULATION_DEATH: 'POPULATION_TOTAL_RECOVERED',
    TOTAL_POPULATION_RECOVERED: 'POPULATION_TOTAL_RECOVERED',
    NEW_POPULATION_CONFIRMED: 'POPULATION_NEW_RECOVERED',
    NEW_POPULATION_DEATH: 'POPULATION_NEW_RECOVERED',
    NEW_POPULATION_RECOVERED: 'POPULATION_NEW_RECOVERED',
}